<?php
use Drupal\Core\Entity\EntityInterface;
use Drupal\demo_module\Event\NodeInsertEvent;

function demo_module_theme() {
    return [
    'demo_module_weather_data' => [
        'variables' => [
            'city' => NULL,
            'temp' => NULL,
        ],
    ],
];
}

function demo_module_node_insert(EntityInterface $node) {
    $ed = \Drupal::service('event_dispatcher');
    $ed->dispatch(
      'node.insert',
      new NodeInsertEvent($node)
    );
  }